### Собственные векторы и собственные значения модельных профилей $MM^{*}$.

### Схема: $\xi = Mn + \nu$

In [1]:
import sys
import numpy as np
sys.path.insert(1, '../scripts')

In [2]:
from profile_recovery import ProfileRec

In [3]:
profile_dir = "profiles_2"
dataset_name = "dataset_3_csv"

In [4]:
from pathlib import Path

for txt_path in sorted(list(Path(Path.cwd().parent, 
                     "data", "profiles_2", 
                     "csv").glob("*.csv"))):
    print(txt_path.name)

threemod_1.csv
threemod_1_1.csv
threemod_2.csv
threemod_2_1.csv
threemod_3.csv
threemod_3_1.csv
threemod_4.csv
threemod_4_1.csv
unimod1000big_1.csv
unimod1000big_2.csv
unimod1000big_3.csv
unimod500big_1.csv
unimod500big_1_1.csv
unimod500big_2.csv
unimod500big_2_1.csv
unimod500big_3.csv
unimod500big_3_1.csv
unimod_1.csv
unimod_1_1.csv
unimod_2.csv
unimod_2_1.csv
unimod_3.csv
unimod_3_1.csv
unimod_4.csv
unimod_4_1.csv
unimod_5.csv
unimod_5_1.csv
unimod_6.csv
unimod_6_1.csv


In [5]:
prof_name = "threemod_1.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

threemod_1.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034]


In [6]:
prof_name = "threemod_1_1.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

threemod_1_1.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034

In [7]:
prof_name = "threemod_2.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

threemod_2.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034]


In [8]:
prof_name = "threemod_2_1.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

threemod_2_1.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034

In [9]:
prof_name = "threemod_3.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

threemod_3.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034]


In [10]:
prof_name = "threemod_3_1.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

threemod_3_1.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034

In [11]:
prof_name = "threemod_4.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

threemod_4.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034]


In [12]:
prof_name = "threemod_4_1.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

threemod_4_1.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034

In [13]:
prof_name = "unimod1000big_1.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod1000big_1.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240

In [14]:
prof_name = "unimod1000big_2.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod1000big_2.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240

In [15]:
prof_name = "unimod1000big_3.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod1000big_3.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240

In [16]:
prof_name = "unimod500big_1.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod500big_1.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.222400

In [17]:
prof_name = "unimod500big_1_1.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod500big_1_1.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.2224

In [18]:
prof_name = "unimod500big_2.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod500big_2.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.222400

In [19]:
prof_name = "unimod500big_2_1.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod500big_2_1.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.2224

In [20]:
prof_name = "unimod500big_3.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod500big_3.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.222400

In [21]:
prof_name = "unimod500big_3_1.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod500big_3_1.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.2224

In [22]:
prof_name = "unimod_1.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod_1.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034]
 [

In [23]:
prof_name = "unimod_1_1.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod_1_1.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034]


In [24]:
prof_name = "unimod_2.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod_2.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034]
 [

In [25]:
prof_name = "unimod_2_1.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod_2_1.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034]


In [26]:
prof_name = "unimod_3.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod_3.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034]
 [

In [27]:
prof_name = "unimod_3_1.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod_3_1.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034]


In [28]:
prof_name = "unimod_4.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod_4.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034]
 [

In [29]:
prof_name = "unimod_4_1.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod_4_1.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034]


In [30]:
prof_name = "unimod_5.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod_5.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034]
 [

In [31]:
prof_name = "unimod_5_1.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod_5_1.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034]


In [32]:
prof_name = "unimod_6.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod_6.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034]
 [

In [33]:
prof_name = "unimod_6_1.csv"
prof_recovery = ProfileRec(prof_name, profile_dir, dataset_name)
rec = prof_recovery.make_data(21)
val, m = np.linalg.eig(np.matmul(np.matrix(rec[1]), 
                                 np.transpose(np.matrix(rec[1]))))
print(prof_name)
for i, v in enumerate(val):
    print(f"eigenvalue[{i}] = {v}")
    print(f"eigenvector[{i}] = \n{m[:, i]}")

unimod_6_1.csv
eigenvalue[0] = 46300.54534232246
eigenvector[0] = 
[[-0.2698913 ]
 [-0.26988872]
 [-0.26970692]
 [-0.26941329]
 [-0.26886717]
 [-0.26798465]
 [-0.26604387]
 [-0.2628016 ]
 [-0.25912948]
 [-0.2516303 ]
 [-0.24595126]
 [-0.23575849]
 [-0.22878994]
 [-0.21748105]
 [-0.19896504]
 [-0.16472387]
 [-0.09260393]
 [-0.05687084]
 [-0.01795838]
 [-0.00281498]
 [ 0.        ]]
eigenvalue[1] = 1339.7567688767754
eigenvector[1] = 
[[-0.23029856]
 [-0.23010409]
 [-0.22841855]
 [-0.22229787]
 [-0.21158686]
 [-0.19329771]
 [-0.13203008]
 [-0.09087535]
 [-0.02670182]
 [ 0.07969153]
 [ 0.14083744]
 [ 0.22211876]
 [ 0.27006396]
 [ 0.32475562]
 [ 0.38530525]
 [ 0.39963349]
 [ 0.28383061]
 [ 0.19206661]
 [ 0.06534723]
 [ 0.00876881]
 [ 0.        ]]
eigenvalue[2] = 202.52832277125782
eigenvector[2] = 
[[ 0.16325937]
 [ 0.16466905]
 [ 0.16207443]
 [ 0.14983355]
 [ 0.12969384]
 [ 0.09597254]
 [-0.06425189]
 [-0.09202056]
 [-0.19020658]
 [-0.29612177]
 [-0.31367627]
 [-0.25238672]
 [-0.22240034]
