In [1]:
import numpy as np

In [7]:
a = np.array([[2, 66],[6, 6]])
b = np.array([[5, 78], [7, 9]])

In [8]:
print(a)
print(b)
print(a @ b)

[[ 2 66]
 [ 6  6]]
[[ 5 78]
 [ 7  9]]
[[472 750]
 [ 72 522]]
